
Use [ASSIGNMENT 3];

ALTER TABLE TEAMS
ADD CONSTRAINT HOME_STADIUM_ID
FOREIGN KEY (HOME_STADIUM_ID)
REFERENCES STADIUMS(ID);

ALTER TABLE PLAYERS_DESCRIPTION
ADD CONSTRAINT PLAYER_ID
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID);
 
ALTER TABLE PLAYERS
ADD CONSTRAINT TEAM_ID
FOREIGN KEY (TEAM_ID) 
REFERENCES TEAMS(ID);

ALTER TABLE MANAGERS
ADD CONSTRAINT TEAMID
FOREIGN KEY (TEAM_ID) 
REFERENCES TEAMS(ID);

ALTER TABLE MATCHES
ADD CONSTRAINT TEAMSID
FOREIGN KEY (HOME_TEAM_ID) 
REFERENCES TEAMS(ID);

ALTER TABLE MATCHES
ADD CONSTRAINT TEAMSID1
FOREIGN KEY (AWAY_TEAM_ID) 
REFERENCES TEAMS(ID);

ALTER TABLE MATCHES
ADD CONSTRAINT STADIUMID
FOREIGN KEY (STADIUM_ID) 
REFERENCES STADIUMS(ID);

ALTER TABLE MATCH_REPORT
ADD CONSTRAINT MATCH_ID
FOREIGN KEY (MATCH_ID) 
REFERENCES MATCHES(MATCH_ID);

ALTER TABLE GOALS
ADD CONSTRAINT GOAL_MATCH_ID
FOREIGN KEY (MATCH_ID) 
REFERENCES MATCHES(MATCH_ID);

ALTER TABLE GOALS
ADD CONSTRAINT GOAL_PLAYERS_ID
FOREIGN KEY (PID) 
REFERENCES PLAYERS(PLAYER_ID);



